export const cards = [
    {
        img: 'assets/product/dc1.jpg',
        name: 'Coffee table "Aurora"',
        price: 69,
        length: 500,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Wood',
        popularity: 38,
    },
    {
        img: 'assets/product/dc2.jpg',
        name: 'Coffee table "Horizon"',
        price: 52,
        length: 650,
        createdFor: 'Decorative',
        shape: 'Square',
        color: 'Black',
        popularity: 76,
    },
    {
        img: 'assets/product/dc3.jpg',
        name: 'Book table "Kinfolk"',
        price: 59,
        length: 320,
        createdFor: 'Decorative',
        shape: 'Square',
        color: 'Wood',
        popularity: 81,
    },
    {
        img: 'assets/product/dc4.jpg',
        name: 'Coffee table "Jenga"',
        price: 79,
        length: 440,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Wood',
        popularity: 12,
    },
    {
        img: 'assets/product/dc5.jpg',
        name: 'Loft table "Plate"',
        price: 52,
        length: 310,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Black',
        popularity: 77,
    },
    {
        img: 'assets/product/dc6.jpg',
        name: 'Coffee table "Flip"',
        price: 63,
        length: 340,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Wood',
        popularity: 26,
    },
    {
        img: 'assets/product/dc7.jpg',
        name: 'Bedside table "Alarm"',
        price: 50,
        length: 290,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'White',
        popularity: 55,
    },
    {
        img: 'assets/product/dc8.jpg',
        name: 'Coffee table "Renaissance"',
        price: 82,
        length: 630,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Wood',
        popularity: 57,
    },
    {
        img: 'assets/product/dc9.jpg',
        name: 'Multifunctional table "Futurist"',
        price: 140,
        length: 800,
        createdFor: 'Decorative',
        shape: 'Square',
        color: 'Wood',
        popularity: 99,
    },
    {
        img: 'assets/product/dc10.jpg',
        name: 'Loft table "Oak"',
        price: 119,
        length: 690,
        createdFor: 'Decorative',
        shape: 'Rounded',
        color: 'Wood',
        popularity: 65,
    },
    {
        img: 'assets/product/dn1.jpg',
        name: 'Dining table "DinLine"',
        price: 380,
        length: 1200,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 74,
    },
    {
        img: 'assets/product/dn2.jpg',
        name: 'Dining table "Simple"',
        price: 190,
        length: 780,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 51,
    },
    {
        img: 'assets/product/dn3.jpg',
        name: 'Dining table "Village"',
        price: 210,
        length: 810,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'White',
        popularity: 78,
    },
    {
        img: 'assets/product/dn4.jpg',
        name: 'Dining table "Heavy"',
        price: 530,
        length: 1300,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 36,
    },
    {
        img: 'assets/product/dn5.jpg',
        name: 'Dining table "Modern"',
        price: 590,
        length: 1500,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'White',
        popularity: 61,
    },
    {
        img: 'assets/product/dn6.jpg',
        name: 'Dining table "Retro"',
        price: 260,
        length: 960,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 85,
    },
    {
        img: 'assets/product/dn7.jpg',
        name: 'Dining table "Strict"',
        price: 365,
        length: 1180,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 17,
    },
    {
        img: 'assets/product/dn8.jpg',
        name: 'Dining table "Cozy"',
        price: 519,
        length: 1010,
        createdFor: 'Dinner',
        shape: 'Square',
        color: 'Wood',
        popularity: 93,
    },
    {
        img: 'assets/product/ot1.jpg',
        name: 'Office conference table "Simple"',
        price: 649,
        length: 1360,
        createdFor: 'Office',
        shape: 'Square',
        color: 'White',
        popularity: 34,
    },
    {
        img: 'assets/product/ot2.jpg',
        name: 'Desk with bedside table "Smart-1"',
        price: 485,
        length: 1090,
        createdFor: 'Office',
        shape: 'Square',
        color: 'White',
        popularity: 71,
    },
    {
        img: 'assets/product/ot3.jpg',
        name: 'Office table "Feature"',
        price: 529,
        length: 980,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 22,
    },
    {
        img: 'assets/product/ot4.jpg',
        name: 'Office table "Minimalism"',
        price: 385,
        length: 800,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 42,
    },
    {
        img: 'assets/product/ot5.jpg',
        name: 'Desk with bedside table "Smart-2"',
        price: 460,
        length: 960,
        createdFor: 'Office',
        shape: 'Square',
        color: 'White',
        popularity: 83,
    },
    {
        img: 'assets/product/ot6.jpg',
        name: 'Office conference table "Massive"',
        price: 1030,
        length: 2100,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 69,
    },
    {
        img: 'assets/product/ot7.jpg',
        name: 'Desk with stands "Smart-3"',
        price: 395,
        length: 990,
        createdFor: 'Office',
        shape: 'Square',
        color: 'White',
        popularity: 13,
    },
    {
        img: 'assets/product/ot8.jpg',
        name: 'Desk with shelves "Graphic"',
        price: 415,
        length: 850,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 31,
    },
    {
        img: 'assets/product/ot9.jpg',
        name: 'Office table "JustWood"',
        price: 310,
        length: 1100,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 52,
    },
    {
        img: 'assets/product/ot10.jpg',
        name: 'Office table "Unusual"',
        price: 500,
        length: 980,
        createdFor: 'Office',
        shape: 'Square',
        color: 'Wood',
        popularity: 88,
    },
];
